### ISSUE TITLE
Each subject should be a struct object instead of a []string

### ISSUE THREAD

**Issue by icyflame** [metakgp/chillzone#1]
Currently, subjects are represented as `[]string`s instead of a `struct` which has [these keys][1].

Doing this will allow us to eliminate the [`change_map_structure`][2] step from the process. The conversion from `[]string` to the `struct` can be done [here][3], by iterating over each element of `dep_val.Subjects` and assigning it to the appropriate field of the struct. Validations can also be put in at this stage (eg: `L-T-P` must be `#-#-#`, Credits must be a valid integer, etc)

[1]: https://github.com/metakgp/chillzone/blob/314b9658132e1bbf28777aea17c1ee7d48f9f57c/change_map_structure.go#L3-L11
[2]: https://github.com/metakgp/chillzone/blob/314b9658132e1bbf28777aea17c1ee7d48f9f57c/main.go#L161
[3]: https://github.com/metakgp/chillzone/blob/314b9658132e1bbf28777aea17c1ee7d48f9f57c/main.go#L120

**Comment by thealphadollar** [comment]
@icyflame Please make me aware of the implications of the same.

**Comment by icyflame** [comment]
There will be no change in the behaviour. This issue is just to remove the `map[string]string` and use a `struct Subject` instead.

```go
type Subject struct {
    Code string
    ...
}

g := Subject{}
fmt.Println(g.Code)
```

Instead of:

```go
g := map[string]string{
    "Code": "1",
}

fmt.Println(g["Code"])
```

It's more flexible and you can write and read from JSON files fairly easily etc.
