### ISSUE TITLE
Web App manifest

### ISSUE THREAD

**Issue by xypnox** [metakgp/chillzone#15]
Add web app manifest so that there can be direct homescreen link through Firefox on android that acts as an app rather than browser.
https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by Hahkarthick** [comment]
Hi, I'll like to contribute will you share the icons.

**Comment by thealphadollar** [comment]
@Hahkarthick I've tagged you in the relevant post. Please create the icon files as well. If you need any help, please ping.

**Comment by Hahkarthick** [comment]
> @Hahkarthick I've tagged you in the relevant post. Please create the icon files as well. If you need any help, please ping.

can you share the icons or merge the icons in repo

**Comment by thealphadollar** [comment]
@Hahkarthick You can create the icons using the tool available here: https://icoconvert.com/

And as said earlier, the image can be found in the respected tag.

**Comment by thealphadollar** [comment]
Also, this should be done in the frontend of chillzone which is availbel here which already has the required icon file: https://github.com/metakgp/chillzone-frontend/

**Comment by thealphadollar** [comment]
Thank you @xypnox and @Hahkarthick for creating and patching this issue. I'm highly grateful for your contributions.

fixed via #22
