### ISSUE TITLE
take place suggestions

### ISSUE THREAD

**Issue by raivivek** [metakgp/chillzone#16]
optionally take suggestions of "where are you now?" and suggest places nearby that OR place/complex to prefer first

**Comment by thescriptninja** [comment]
I think adding an option of choosing the floor(1, 2, 3, 4) and complex (NC/NR) might be useful. Maybe create a dropdown next to the existing day and time dropdowns with a default option of 'Any'.

**Comment by thealphadollar** [comment]
Yes. I guess that should be easy and then you can show the rooms that correspond to the same. This should be very easy to implement. Would you like to work on this, @thescriptninja

**Comment by thescriptninja** [comment]
Ok. I'll send a PR to the frontend repository.

**Comment by thealphadollar** [comment]
Thanks Parth.

**Comment by thescriptninja** [comment]
@thealphadollar done.

**Comment by thealphadollar** [comment]
closing via https://github.com/metakgp/chillzone-frontend/pull/4
