### ISSUE TITLE
get a logo

### ISSUE THREAD

**Issue by raivivek** [metakgp/chillzone#17]
Logos are nice. Help build visibility. If not possible by self, get someone else to help you out and provide them due credit for help. Collaboration is great.

**Comment by Dattax** [comment]
Hi, I'm looking for issues to help with - does this still need a logo? I can make one (any requirements?)

**Comment by thealphadollar** [comment]
Yes, surely. There are no such requirements but keep it as close
as possible to what the app serves.

**Comment by Dattax** [comment]
I have created 3 logo files and sent you a pull request. You may want to place them in a img folder.

**Comment by raivivek** [comment]
Thanks! I think it's okay to leave IIT Kharagpur out the logo.

**Comment by Dattax** [comment]
ok great!

**Comment by thealphadollar** [comment]
fixed via https://github.com/metakgp/chillzone/pull/18
