### ISSUE TITLE
Add Method to parse first year time table from PDF

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/chillzone#19]
Currently, we have to manually enter the first year time table.

The first year timetable is avaiable in the central timetable PDF; a PDF parsing method can be used to automate the process.

**Comment by thealphadollar** [comment]
Please take note of the below details and the solution provided.

From page 3 of [Central Timetable](https://erp.iitkgp.ac.in/Acad/Aut_Time_Table_19_20.pdf) the time table for first years begin.

In the [CSV template](https://github.com/metakgp/chillzone/blob/master/first-year.csv.template) we add each course with the room that it'll be occupying and the slot along with trivial information like it's code, credit etc.

A [CSV](https://github.com/metakgp/chillzone/blob/master/first-year.csv) filled for [Spring 2018-2019](https://erp.iitkgp.ac.in/Acad/timetable_SPR2018.pdf) is available. This CSV has been filled in a manner that the slot distribution was available and I could simply fill it from there so there was no need for automation as it was just two pages.

Now, the slot distribution is not there and hence we need to automate since nobody is going through the hasttle of adding for 20 sections.

The way to automate would be; first store a dictionary having information about all the slots and which days those slots belong to. Then going through each of the section timetable, we should be marking the room number, subject number and the slot. We should also be storing subject information. Once this is done, out the dictionary as a CSV.

@thescriptninja Please work with Sriyash

**Comment by thescriptninja** [comment]
Sure :+1:
