### ISSUE TITLE
Separation between data and code

### ISSUE THREAD

**Issue by kshitij10496** [metakgp/chillzone#2]
While reading through the codebase, I found a couple of instances where we have hardcoded data:
- `departments` in `main.go`
- `rooms` in `rooms.go`

We can migrate these to their respective JSON files and read the data into the program whenever necessary. This will also help us abstract lots of details into useful and extensible data structures.

**Comment by kshitij10496** [comment]
For instance, I tried to implement this for the `departments` as follows:

**departments.json**
``` departments.json
{
  "departments": [
    {
      "code": "AE"
    },
    {
      "code": "AG"
    },
    {
      "code": "AR"
    },
    {
      "code": "AT"
    },
    {
      "code": "BE"
    },

```
**departments.go**
``` departments.go
type Departments struct {
	Departments []Department `json:"departments"`
}

type Department struct {
	Code string `json:"code"`
}

func GetDepartments(filename string) ([]Department, error) {
	data, err := ioutil.ReadFile(filename)
	if err != nil {
		return nil, err
	}

	var departments Departments
	err = json.Unmarshal(data, &departments)
	if err != nil {
		return nil, err
	}
	return departments.Departments, nil
}
```
This way we can add more information to JSON(such as Full Name, Classes) as required without affecting our program.

**Comment by icyflame** [comment]
NICE! I was going to add this as an issue, although I wasn't sure if it would be too mundane for an issue and I should have gone out there and done it myself. Please open a patch with this, others can emulate your pattern, since you already seem to have code.
