### ISSUE TITLE
Transparency regarding what is meant by "empty" classrooms

### ISSUE THREAD

**Issue by chirag-ghosh** [metakgp/chillzone#47]
**Is your feature request related to a problem? Please describe.**
Users think that the classrooms listed as empty are meant to be available as "free to use". This is not always the case. Classrooms listed as empty only mean that those rooms are supposed to be free of any classes according to the timetable at ERP. Many a times professors change the classroom which is not reflected in ERP. Also suppose a classroom has no classes in a particular day, it is possible that the guards might decide to not unlock the room at all making it inaccessible (very often the case with Vikramshila classrooms).

**Describe the solution you'd like**
Show a single line info banner on top of the website with a text like "The empty classes listed below might not be accurate in real life." There will also be a learn more button which will redirect to a page which clearly explains the various situations described above.

**Describe alternatives you've considered**
People will understand - Does not work

**Comment by himanchal08** [comment]
Hello there I'd like to solve this issue please assign this issue to me .

**Comment by chirag-ghosh** [comment]
@himanchal08 just to confirm. You are a current student of IITKGP right?
Else you might not have context nor proper access to the website

**Comment by himanchal08** [comment]
I do not studying in currently in IITKGP . 
But explain me a little I'II understand.

**Comment by himanchal08** [comment]
Hello there, I am unable to setup your repository as I am a newbie please
help me do it. I it will help me to learn a lot of new things.

Your help is much appreciated.

**Comment by chirag-ghosh** [comment]
The installation instructions are written in the repo readme [here](https://github.com/metakgp/chillzone?tab=readme-ov-file#local-installation).
Have you tried it?
If so, what are the issues you faced. Please provide with screenshots or error message if any.

**Comment by himanchal08** [comment]
The issue Is I installed pnpm but its not working.

**Comment by chirag-ghosh** [comment]
Without any error message or screenshot I won't be able to debug the issue. Please provide the same.
Also please provide details regarding your Operating System.

Also maybe try googling the issue. There is a good probability that your issue is already fixed by someone.

For more info on asking better questions, please read: http://www.catb.org/esr/faqs/smart-questions.html

**Comment by himanchal08** [comment]
I am currently using W 11 and I have installed pnpm but the html is still
not working. Is there any json I should be altering or something else.
These are the issues that I am facing.

**Comment by chirag-ghosh** [comment]
I cannot really what you mean by "HTML is not loading".

Please share what exact commands you ran on the terminal and what were their responses

**Comment by himanchal08** [comment]
These are the exact commands I am using and issues I am facing.

**Comment by Hurricane0017** [comment]
Hey, I would like to solve this issue, please assign this to me

**Comment by chirag-ghosh** [comment]
@himanchal08 you are typing the commands in the terminal right?
I need to see the corresponding output of those commands.

If you still can't understand, please create a screen recording showing how you are running the project and the issue.

Please do this by today or I'll have to reassign this issue to someone else

**Comment by himanchal08** [comment]
Thank you for your concern but all the issues are solved and the project is
locally host in my machine. Now I am working on the issues .

Thanks You

**Comment by chirag-ghosh** [comment]
@himanchal08 updates?

**Comment by chirag-ghosh** [comment]
@himanchal08 since there is no update frpm you since 2 weeks, I'll be going forward with the other PRs
