### ISSUE TITLE
 Failed to compile ./src/Utilities.js Line 29:  'AbortController' is not defined 

### ISSUE THREAD

**Issue by milinddethe15** [metakgp/chillzone#49]
**Describe the bug**
Running `npm start` in frontend gave error:
```
 Failed to compile
./src/Utilities.js
  Line 29:  'AbortController' is not defined  no-undef
```
AbortController must be imported to solve this error.

**Can I make a PR for this?**

**Screenshots**
![image](https://github.com/metakgp/chillzone/assets/99114125/861f76be-63ca-4e01-8760-125180756ae2)

**Comment by shikharish** [comment]
Hi @milinddethe15 
Which nodejs version are you using?

**Comment by milinddethe15** [comment]
node -v
v18.17.0

**Comment by shikharish** [comment]
@milinddethe15 
Instead of `npm` use `pnpm`

**Comment by milinddethe15** [comment]
Thanks. Now it is working. Readme file needs changes.
