### ISSUE TITLE
IIT KGP CONNECTION FOR LOCAL DEV

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [metakgp/chillzone#56]
As we open the website it shows that we need to be connected to IITKGP network . How to overcome this issue in local development 
![image](https://github.com/metakgp/chillzone/assets/91052168/61899625-fe27-44ac-9b86-723bc2f2ac8d)

**Comment by Swarnendu0123** [comment]
> As we open the website it shows that we need to be connected to IITKGP network . How to overcome this issue in local development ![image](https://private-user-images.githubusercontent.com/91052168/285745301-61899625-fe27-44ac-9b86-723bc2f2ac8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTQ3MzQsIm5iZiI6MTcwMTE1NDQzNCwicGF0aCI6Ii85MTA1MjE2OC8yODU3NDUzMDEtNjE4OTk2MjUtZmUyNy00NGFjLTliODYtNzIzYmMyZjJhYzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA2NTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZmZiZmVjNzQzMjM0YTU3YWFhZmQ3N2VmODVkMjM3MWM4MTFjM2E5MjYxOGRhODdlNmYzNDBjODRlOTQ0NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D8b6K6BwPiPp4VMkKFW1jPaG2E38ECgoQiJc8RFqlcE)

Hey @VineeTagarwaL-code , Comment this lines in App.js and here you go...
![Screenshot (28)](https://github.com/metakgp/chillzone/assets/94161758/d0f8df3f-4005-4fdf-ae10-5c5777dd69bb)

**Comment by VineeTagarwaL-code** [comment]
yeah i did that , worked
