### ISSUE TITLE
Automatic deployment of frontend

### ISSUE THREAD

**Issue by chirag-ghosh** [metakgp/chillzone#64]
Currently we need to manually deploy frontend by creating a build in local and running `pnpm run deploy`. Automate this process such that the deployment is always from the most updated version of the `master` branch. Additionally create another github action which builds the frontend whenever there is a PR and allows merge only if the build was successful.

Tasks:
- [ ] Automatically build and deploy from the `master` branch
- [ ] Check whether the frontend build is successful for each PR.

**Comment by Bikram-ghuku** [comment]
Can I work on this issue?

**Comment by proffapt** [comment]
Interesting. Go ahead.
