### ISSUE TITLE
[BUG] Doesn't fetch time table for breadths

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/chillzone#7]
Currently the backend is unable to fetch time table for breadths [confirmed for
2018-2019 AUTUMN HSS].

It shows misleading data to users of chillzone.

The solution could be creation of a standalone API (integration is also not discouraged) which can be called using REST API. It can also be used, then, with other projects under metaKGP.

**Comment by icyflame** [comment]
@thealphadollar It's good that you have opened the issue. But a good issue should have the following 4 ingredients to be useful.

[x] What is the problem?
[ ] Why is this a problem? (_Incorrectly shows a lot of rooms as empty, leading to misleading information on chillzone_)
[ ] Why does the current code fail to solve this problem? If a particular section of the code is buggy, what section? If this is not known, mention that. A contributor willing to track down the buggy section of code is just as useful as a contributor who will fix the bug.
[ ] What is an acceptable maintainer suggested method of solving this problem? This is mainly for people who want to immediately dip their foot in and solve the problem. This is only one possible solution, a patch using this solution approach _must_ be accepted as long as it's a good patch. This guarantee from the maintainer's side ensures that no one will end up 

For new features, there will be some basic changes in the format, rest should remain the same.

I haven't really followed this format in the past, but I now realize that without these components an issue is not informative enough for a contributor to work on.

**Comment by icyflame** [comment]
@thealphadollar It's good that you have opened the issue. But a good issue should have the following 4 ingredients to be useful.

[x] What is the problem?
[ ] Why is this a problem? (_Incorrectly shows a lot of rooms as empty, leading to misleading information on chillzone_)
[ ] Why does the current code fail to solve this problem? If a particular section of the code is buggy, what section? If this is not known, mention that. A contributor willing to track down the buggy section of code is just as useful as a contributor who will fix the bug.
[ ] What is an acceptable maintainer suggested method of solving this problem? This is mainly for people who want to immediately dip their foot in and solve the problem. This is only one possible solution, a patch using this solution approach _must_ be accepted as long as it's a good patch. This guarantee from the maintainer's side ensures that no one will end up 

For new features, there will be some basic changes in the format, rest should remain the same.

I haven't really followed this format in the past, but I now realize that without these components an issue is not informative enough for a contributor to work on.

**Comment by thealphadollar** [comment]
@icyflame My sincere apologies for such a misinformed issue, but I just kept the issue as a reminder to myself to work on this. This issue wasn't intended to be taken up by others and hence such lack of information.

**Comment by icyflame** [comment]
@thealphadollar I am sure your intentions were good :) But I have noticed that despite how much we intend to work on a feature, if we are opening an issue instead of opening a patch for the issue, that means we don't have the time to work on it and must come back to it in the future. I have been unable to work on a lot of issues like this. That's why whenever I open an issue, I always make it so anyone can work on it.

In any case, please add the required information to the issue. :)

**Comment by thealphadollar** [comment]
@icyflame I've added information as much as I'm aware of :disappointed:

**Comment by thealphadollar** [comment]
This was not a bug but a mistake from my side; added to POSTMORTEM.md
