### ISSUE TITLE
Chillzone not opening on campus network

### ISSUE THREAD

**Issue by Bikram-ghuku** [metakgp/chillzone#81]
**Describe the bug**
Chillzone makes requests to wrong endpoint to check if on campus network
https://github.com/metakgp/chillzone/blob/ff22decb84918c91668329b01f4c611aa4982888/frontend/src/constants/constants.ts#L1

**To Reproduce**
1. Login to `heimdall`
2. Go to chillzone

**Expected behavior**
Should open the website as I am on Campus network

**Screenshots**
![image](https://github.com/metakgp/chillzone/assets/37508038/3f716cb1-8da0-43db-9727-fd8e3d2efd5f)

**Desktop (please complete the following information):**
 - OS:  Not specific
 - Browser: not specific
 - Version: latest

**Additional context**
Fix to send the request to proper endpoint

**Comment by chirag-ghosh** [comment]
It should use the new url: https://heimdall-api.metakgp.org/campus-check
Can you please make a PR making the change?

**Comment by Bikram-ghuku** [comment]
Sure
